### ISSUE TITLE
Variable $ISABELLE_LAMBDAPI undefined in lib/Tools/dedukti_test

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/isabelle_dedukti#3]
`isabelle dedukti_test` fails because $ISABELLE_LAMBDAPI is not set.

Should this variable be set by the user? This is not explained in the README.

In addition, the script `lib/Tools/dedukti_test` seems to have another problem: because of the use of double quotes, $ISABELLE_LAMBDAPI cannot be set to `lambdapi check`:

```
18:55 ~/src/isabelle_dedukti (master) isabelle dedukti_test
Importing theory Pure
Importing theory Tools.Code_Generator
Importing theory HOL.HOL
Importing theory HOL.Ctr_Sugar
Importing theory HOL.Orderings
Importing theory HOL.Groups
Importing theory HOL.Lattices
Importing theory HOL.Set
Importing theory HOL.Fun
Importing theory HOL.Complete_Lattices
Importing theory HOL.Inductive
0:00:46 elapsed time
lambdapi: unknown command `output.lp'.
Usage: lambdapi COMMAND ...
Try `lambdapi --help' for more information.
```

By using `set -x`, we get:
```
19:12 ~/src/isabelle_dedukti (master) lib/Tools/dedukti_test 
+ OUTPUT=output.lp
++ dirname output.lp
+ cd .
++ basename output.lp
+ 'lambdapi check' output.lp
lib/Tools/dedukti_test: ligne 11: lambdapi check : commande introuvable
```

Finally, a lambdapi.pkg file is missing.

**Comment by makarius** [comment]
The default for `ISABELLE_LAMBDAPI` is provided by `etc/settings` of the Isabelle component configuration, see https://github.com/Deducteam/isabelle_dedukti/blob/4f451db990ed/etc/settings#L15

Users may override this in `$ISABELLE_HOME_USER/etc/settings` as usual, see also the *system* manual of Isabelle (e.g. via `isabelle doc system`.

Normally everything is properly quoted in Isabelle bash scripts, in order to allow spaces in directory names. In rare situations this is violated, to allow options as part of the command name (this is somewhat historic). There are at least two possibilities:

  * Omit the quotes in `lib/Tools/dedukti_build` to make it more convenient (and a bit more fragile).
  * Provide something like `ISABELLE_LAMBDAPI_OPTIONS` in addition to the command name.

**Comment by fblanqui** [comment]
@yannl35133 Is it still an issue?

**Comment by yannl35133** [comment]
`dedukti_test` now uses `lambdapi init` and `make` with the generated Makefile (where lambdapi is $ISABELLE_LAMBDAPI, currently set in etc/settings).
So it shouldn't be an issue anymore
