### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by yannl35133** [Deducteam/isabelle_dedukti#4]
Report here but the bug most likely lies in Isabelle proper.

Trying to export up to HOL.Zorn, and got a dependency problem between HOL.Sum_Type and HOL.Product_Type

`proof408788` is defined in HOL.Product_Type, used in HOL.Sum_Type but the latter does not reference the former.

ROOT
```
[...]
session Isabelle_Export in "Ex/Export" = Pure +
  options [export_theory, export_proofs, record_proofs = 2]
  sessions HOL
  theories
    HOL.List
```

bash
```bash
isabelle dedukti_build && isabelle dedukti_import -O "test/main.lp" Isabelle_Export
```

Appears both on master and on my fork (which supports today's lambdapi)

I'm still quite new and don't know everything about this, so this may be my fault

**Comment by fblanqui** [comment]
Makarius said:

The problem is actually on the isabelle_dedukti side, where some "proof box" is
written to the wrong theory output: Product_Type instead of its origin
Complete_Lattices.

Note that isabelle.Export_Theory.read_proof_boxes returns individual Thm_Id
values, with an indication to which theory it belongs: it has to be exported
to the correct file to make the import work.

The problem is a consequence of the split into individual lp files done here:
https://github.com/Deducteam/isabelle_dedukti/blob/ebd9fcfebf91/src/importer.scala#L161
--- instead of prose comments it would be better to represent the idea clearly
in Scala, using functions and/or classes to manage all theories together (this
requires some practice and proficiency with Scala).

**Comment by fblanqui** [comment]
@yannl35133 Is it still an issue?

**Comment by yannl35133** [comment]
It shouldn't be anymore
